### ISSUE TITLE
something about the config file

### ISSUE THREAD

**Issue by hanleilei** [briandfoy/Module-Starter-AddModule#2]
I try add this module to add more module file in my repo, here is some example:

HanLei-MacBook-Pro:perl hanlei$ module-starter --module=Animal,Animal::Sheep,Animal::Cow --author="Oliver" --email=han.oliver@me.com --verbose
Created Animal
Created Animal/lib
Created Animal/lib/Animal.pm
Created Animal/lib/Animal
Created Animal/lib/Animal/Sheep.pm
Created Animal/lib/Animal/Cow.pm
Created Animal/t
Created Animal/t/pod.t
Created Animal/t/00-load.t
Created Animal/t/pod-coverage.t
Created Animal/t/manifest.t
Created Animal/xt
Created Animal/xt/boilerplate.t
Created Animal/ignore.txt
Created Animal/Makefile.PL
Created Animal/Changes
Created Animal/README
Added to MANIFEST: Changes
Added to MANIFEST: ignore.txt
Added to MANIFEST: lib/Animal.pm
Added to MANIFEST: lib/Animal/Cow.pm
Added to MANIFEST: lib/Animal/Sheep.pm
Added to MANIFEST: Makefile.PL
Added to MANIFEST: MANIFEST
Added to MANIFEST: README
Added to MANIFEST: t/00-load.t
Added to MANIFEST: t/manifest.t
Added to MANIFEST: t/pod-coverage.t
Added to MANIFEST: t/pod.t
Added to MANIFEST: xt/boilerplate.t
Created Animal/MANIFEST
Created starter directories and files
HanLei-MacBook-Pro:perl hanlei$ cd Animal/
HanLei-MacBook-Pro:Animal hanlei$ ls
Changes		MANIFEST	Makefile.PL	README		ignore.txt	lib		t		xt
HanLei-MacBook-Pro:Animal hanlei$ module-starter --module=Animal::Horse --dist=.
Must specify an email address
 at /Library/Perl/5.18/Module/Starter/App.pm line 134.
HanLei-MacBook-Pro:Animal hanlei$ module-starter --module=Animal::Horse --distro=.
Must specify an email address
 at /Library/Perl/5.18/Module/Starter/App.pm line 134.
HanLei-MacBook-Pro:Animal hanlei$ module-starter --module=Animal::Horse --dist=. --email=han.oliver@me.com
. already exists.  Use --force if you want to stomp on it.

Now, I'm totally lost, could you please tell me how to handle the configure file? there is no info in Module::Starter module's document and Module::Starter::AddModule module's document.

Great appreciate

Oliver

**Comment by briandfoy** [comment]
You're using the module-starter program, so look for its documentation: perldoc module-starter.
