### ISSUE TITLE
Plugin fails under windows

### ISSUE THREAD

**Issue by BillKSmith** [briandfoy/module-starter-addmodule#3]
Attempted to duplicate the example from the book "Intermediate Perl" 2nd edition (Page 182), using Windows 7 Professional, Service Pack 1, 64-bit and Strawberry perl 5.24.1.

Plusgin failed with an error message from Windows.

'.' is not recognized as an internal or external command,

Corion identified the problem and syphilis proposed a fix in permonks.com node_id=1219609 which solves my problem.

Change line 194
from
            system( './Build', 'manifest' );
to
	system( $^X, './Build', 'manifest' ); #ref perlmonks id 1219584

I have not attempted to demonstrate the problem or the fix in any other configuration.

**Comment by briandfoy** [comment]
The Perlmonks link is https://www.perlmonks.org/?node_id=1219584

Sorry this took so long. There was a long period where I wasn't getting Github notifications (or paying attention to Perlmonks).

You noted this was your first time filing an issue, and even though I dropped the ball on this, you did pretty well. It's a clear description of the problem and you pointed to a fix. Well done!

**Comment by BillKSmith** [comment]
Thanks for this reply.   Sorry about my insulting comments concerning your book.  I was frustrated by this problem and by another I had discussed in https://www.perlmonks.com/?node_id=1163744
