### ISSUE TITLE
Module::Starter::AddModule w/ Module::Starter::PBP

### ISSUE THREAD

**Issue by dci2112** [briandfoy/module-starter-addmodule#4]
Using a module-starter/config with the plugins line:

`plugins: Module::Starter::AddModule Module::Starter::PBP`

or the reverse ordering fails to provide the functionality of both. Are they incompatible? The above ordering gets the correct utilization of the templating in Module::Starter::PBP, but it doesn't support adding modules to an existing distribution...

`module-starter --module=My::New::SubModule --dist=.`

Errors about '. already exists'. When the subclassing ordering is reversed in the config, then the module add works but it ignores the PBP templating.

I am unsure if this is a problem in module-starter's plugin loading, or Module::Starter::AddModule, or Module::Starter::PBP. 

I also cannot get Module::Starter::PBP to work with Module::Starter::Smart.

I apologize if I logged this defect under the wrong distro, but I had to start somewhere =(.

**Comment by briandfoy** [comment]
Did you discover anything more about this issue?

**Comment by briandfoy** [comment]
The problem appears to be that `Module::Starter::PBP` calls `exit` in its import routine, so it won't allow other plugins to do their thing. But, since `Module::Starter::PBP` has been unmaintained for 15 years, you probably shouldn't be using it.
